/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoVien;

import Model.GiaoVien.ListBuoiHoc;
import Model.GiaoVien.ReadWriteMyEnum;
import Model.MyEnum;
import TableModel.GiaoVien.ComboBoxCellEditor_ExportExcelSetting;
import TableModel.GiaoVien.ComboBoxCellEditor_RollUp;
import TableModel.GiaoVien.RollUpStudentTableModel;
import TableModel.GiaoVien.TblRendererLookUp;
import TableModel.GiaoVien.TblRenderer_ExportExcelSetting;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chuon
 */
public class ExportExcelSetting extends javax.swing.JDialog {
    
    private String tenDangNhap;
    private DefaultTableModel tblModel;
    /**
     * Creates new form ExportExcelSetting
     */
    public ExportExcelSetting(java.awt.Frame parent, boolean modal, String tenDangNhap) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cài Đặt Kết Xuất File Excel");
        this.tenDangNhap = tenDangNhap;
        tblModel = (DefaultTableModel) tbl.getModel();
        firstSetUp();
    }

    private void firstSetUp() {
        showTable();
        setTableProperties();
        setTblEditor();
        setTblRenderer();
        tblModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent tme) {
                tbl.repaint();
            }
        });
    }

    private void showTable() {
        tblModel.setRowCount(0);
        MyEnum cellValue = MyEnum.CO_MAT;
        tblModel.addRow(new Object[]{cellValue.getChuThichEditorComBoBox(),
            cellValue.getKyHieuExcel(), cellValue.getBackGroundColorKyHieuExcel()});
        cellValue = MyEnum.HOC_MUON;
        tblModel.addRow(new Object[]{cellValue.getChuThichEditorComBoBox(),
            cellValue.getKyHieuExcel(), cellValue.getBackGroundColorKyHieuExcel()});
        cellValue = MyEnum.VANG_KO_PHEP;
        tblModel.addRow(new Object[]{cellValue.getChuThichEditorComBoBox(),
            cellValue.getKyHieuExcel(), cellValue.getBackGroundColorKyHieuExcel()});
        cellValue = MyEnum.VANG_CO_PHEP;
        tblModel.addRow(new Object[]{cellValue.getChuThichEditorComBoBox(),
            cellValue.getKyHieuExcel(), cellValue.getBackGroundColorKyHieuExcel()});
    }

    private void setTableProperties() {
        // tuy chinh cac propeties linh tinh cua table
        tbl.setRowHeight(22);
        tbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        // no cell Selection Mode
        //tblStudents.setCellSelectionEnabled(true);
        tbl.getTableHeader().setReorderingAllowed(false);
        // tuy chinh chieu rong cua cac cot
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
            tbl.getColumnModel().getColumn(2).setResizable(false);
        }
    }

    private void setTblEditor() {
        ComboBoxCellEditor_ExportExcelSetting comboCellEditor = new ComboBoxCellEditor_ExportExcelSetting();
        int column_BackGroundColorKyHieuDiemDanh = 2;
        tbl.getColumnModel().getColumn(column_BackGroundColorKyHieuDiemDanh).setCellEditor(comboCellEditor);
    }

    private void setTblRenderer() {
        TblRenderer_ExportExcelSetting tblRenderer = new TblRenderer_ExportExcelSetting();
        for (int i = 0; i < tbl.getColumnModel().getColumnCount(); i++) {
            tbl.getColumnModel().getColumn(i).setCellRenderer(tblRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDongY = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDongY.setBackground(new java.awt.Color(255, 255, 255));
        btnDongY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDongY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/ok.png"))); // NOI18N
        btnDongY.setText("Đồng Ý");
        btnDongY.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });
        getContentPane().add(btnDongY, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 213, 80, 40));

        btnHuy.setBackground(new java.awt.Color(255, 255, 255));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/Button-Close-icon-16.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 212, 80, 40));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Loại Điểm Danh", "Ký Hiệu", "Màu Nền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 615, 114));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cài Đặt Kết Xuất Excel");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, 33));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        // duyet tung dong, tblModel.get cac value roi MyEnum.set cac value tuong ung
        
        boolean flag = false;
        int column_KyHieu = 1;
        int column_BackGroundColorKyHieuDiemDanh = 2;
        int rowNow = 0;
        for(MyEnum e : MyEnum.values()) {
            String kyHieu = (String) tblModel.getValueAt(rowNow, column_KyHieu);
            short backGroundColorKyHieu = (short) tblModel.getValueAt(rowNow, column_BackGroundColorKyHieuDiemDanh);
            e.setKyHieuExcel(kyHieu);
            e.setBackGroundColorKyHieuExcel(backGroundColorKyHieu);
            rowNow++;
            if (e == MyEnum.VANG_CO_PHEP) {
                flag = true;
            }
        }
        if(flag && ReadWriteMyEnum.writeMyEnum(tenDangNhap)){
            JOptionPane.showMessageDialog(this, "Lưu Thành Công!",
                    "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Lưu Thất Bại",
                    "Thông Báo", JOptionPane.ERROR_MESSAGE);
        }
        // writeMyEnum voi tenDangNhap o tren
    }//GEN-LAST:event_btnDongYActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportExcelSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportExcelSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportExcelSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportExcelSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExportExcelSetting dialog = new ExportExcelSetting(new javax.swing.JFrame(), true, "GV001");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
