/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoVien;

import Model.GiaoVien.KetNoiSQL_GV;
import Model.GiaoVien.ReadWriteMyEnum;
import View.ChangePasswordDlg;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author chuon
 */
public class Info_GVPanel extends javax.swing.JPanel {

    /**
     * Creates new form Info_GV
     */
    private MainFormGV home;
    private String tenDangNhap = KetNoiSQL_GV.getMaGV();
    
    public Info_GVPanel(MainFormGV home) {
        initComponents();
        this.home = home;
        showDataGV();
    }
    
    public void showDataGV(){
        String user = "sa";
        String pass = "123";
        String url = "jdbc:sqlserver://;databaseName=CNPHANMEM3";
        Connection connection = null;
        Statement statement = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(url, user, pass);
            String sql = "select * from dbo.GiaoVien where MaGV=?";
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(1, KetNoiSQL_GV.getMaGV()); 
            ResultSet resultSet = ps.executeQuery();
            txtMaGV.setText(KetNoiSQL_GV.getMaGV());
            while (resultSet.next()) {
                txtHoTenGV.setText(resultSet.getNString("HoTenGV"));
                txtGioiTinh.setText(resultSet.getNString("GioiTinh"));
                txtNgaySinh.setText(new SimpleDateFormat("dd/MM/yyyy").format(resultSet.getDate("NgaySinh")));
                          
            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Info_GVPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JLabel();
        txtHoTenGV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnDoiMatKhau = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCaiDatKetXuatExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN CÁ NHÂN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mã GV");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 180, 23));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Họ Và Tên");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 180, 26));

        txtMaGV.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        txtMaGV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMaGV.setText("jLabel2");
        txtMaGV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtMaGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 340, 23));

        txtHoTenGV.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        txtHoTenGV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHoTenGV.setText("jLabel3");
        txtHoTenGV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHoTenGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 340, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CÀI ĐẶT");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 280, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 211, 638, 10));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mật Khẩu");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 89, 29));

        btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, 31));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày Sinh");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 180, 24));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Giới Tính");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 180, 23));

        txtGioiTinh.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        txtGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtGioiTinh.setText("jLabel6");
        txtGioiTinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 340, 26));

        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        txtNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNgaySinh.setText("jLabel7");
        txtNgaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 340, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kết Xuất Excel");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, 26));

        btnCaiDatKetXuatExcel.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnCaiDatKetXuatExcel.setText("Thay đổi");
        btnCaiDatKetXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaiDatKetXuatExcelActionPerformed(evt);
            }
        });
        add(btnCaiDatKetXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 107, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        ChangePasswordDlg dlg = new ChangePasswordDlg(home, true, tenDangNhap);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnCaiDatKetXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaiDatKetXuatExcelActionPerformed
        new ExportExcelSetting(home, true, tenDangNhap).setVisible(true);
    }//GEN-LAST:event_btnCaiDatKetXuatExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaiDatKetXuatExcel;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtGioiTinh;
    private javax.swing.JLabel txtHoTenGV;
    private javax.swing.JLabel txtMaGV;
    private javax.swing.JLabel txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
