/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoVien;

import Model.GiaoVien.KetNoiSQL_GV;
import Model.GiaoVien.ListBuoiHoc;
import Model.GiaoVien.ReadWriteMyEnum;
import View.LogInDialog;

/**
 *
 * @author chuon
 */
public class MainFormGV extends javax.swing.JFrame {

    private LogInDialog loginDlg;
    private TimeTablePanel timeTablePnl;
    private RollUpMainPanel rollUpPnl;
    private LookUpPanel lookUpPnl;
    private MailPanel mailPnl;
    private Info_GVPanel infoPnl;
    private ListBuoiHoc listBuoiHoc;

    /**
     * Creates new form MainForm
     */
    public MainFormGV() {
        initComponents();
        setLocationRelativeTo(null);
        this.loginDlg = loginDlg;
//          logInDlg = new LogInDialog(this, true);
//        logInDlg.setVisible(true);
        KetNoiSQL_GV.setMaGV("GV001");
        timeTablePnl = new TimeTablePanel();
        mainTPL.addTab("Thời Gian Biểu", timeTablePnl);
        rollUpPnl = new RollUpMainPanel(this);
        mainTPL.addTab("Điểm Danh", rollUpPnl);
        lookUpPnl = new LookUpPanel(this);
        mainTPL.addTab("Tra Cứu", lookUpPnl);
        mailPnl = new MailPanel(this);
        mainTPL.addTab("Hộp Thư", mailPnl);
        mainTPL.setSelectedComponent(rollUpPnl);
        ReadWriteMyEnum.readMyEnum(KetNoiSQL_GV.getMaGV());
    }

    public MainFormGV(LogInDialog logInDialog) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản Lý Điểm Danh PTIT");
        this.loginDlg = logInDialog;
        timeTablePnl = new TimeTablePanel();
        mainTPL.addTab("Thời Gian Biểu", timeTablePnl);
        rollUpPnl = new RollUpMainPanel(this);
        mainTPL.addTab("Điểm Danh", rollUpPnl);
        lookUpPnl = new LookUpPanel(this);
        mainTPL.addTab("Tra Cứu", lookUpPnl);
        mailPnl = new MailPanel(this);
        mainTPL.addTab("Hộp Thư", mailPnl);
        mainTPL.setSelectedComponent(rollUpPnl);
        ReadWriteMyEnum.readMyEnum(KetNoiSQL_GV.getMaGV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        thoiGBBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        diemDanhBtn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        traCuuBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        hopThuBtn = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        thongTinBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        dangXuatBtn = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTPL = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(0, 102, 102));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToolBar1.add(jSeparator1);

        thoiGBBtn.setBackground(new java.awt.Color(255, 255, 255));
        thoiGBBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoiGBBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/calendar-background-icon-16.png"))); // NOI18N
        thoiGBBtn.setText("THỜI GIAN BIỂU");
        thoiGBBtn.setFocusable(false);
        thoiGBBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thoiGBBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thoiGBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoiGBBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(thoiGBBtn);
        jToolBar1.add(jSeparator2);

        diemDanhBtn.setBackground(new java.awt.Color(255, 255, 255));
        diemDanhBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diemDanhBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/diemdanh.jpg"))); // NOI18N
        diemDanhBtn.setText("ĐIỂM DANH");
        diemDanhBtn.setFocusable(false);
        diemDanhBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        diemDanhBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        diemDanhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemDanhBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(diemDanhBtn);
        jToolBar1.add(jSeparator5);

        traCuuBtn.setBackground(new java.awt.Color(255, 255, 255));
        traCuuBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        traCuuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/search-icon-16.png"))); // NOI18N
        traCuuBtn.setText("TRA CỨU");
        traCuuBtn.setFocusable(false);
        traCuuBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        traCuuBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        traCuuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traCuuBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(traCuuBtn);
        jToolBar1.add(jSeparator4);

        hopThuBtn.setBackground(new java.awt.Color(255, 255, 255));
        hopThuBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hopThuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/mail.jpg"))); // NOI18N
        hopThuBtn.setText("HỘP THƯ");
        hopThuBtn.setFocusable(false);
        hopThuBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hopThuBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hopThuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hopThuBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(hopThuBtn);
        jToolBar1.add(jSeparator7);

        thongTinBtn.setBackground(new java.awt.Color(255, 255, 255));
        thongTinBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thongTinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/Person-Male-Light-icon-16.png"))); // NOI18N
        thongTinBtn.setText("THÔNG TIN");
        thongTinBtn.setFocusable(false);
        thongTinBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongTinBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongTinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongTinBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(thongTinBtn);
        jToolBar1.add(jSeparator3);

        dangXuatBtn.setBackground(new java.awt.Color(255, 255, 255));
        dangXuatBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dangXuatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/logout-icon-16.png"))); // NOI18N
        dangXuatBtn.setText("ĐĂNG XUẤT");
        dangXuatBtn.setFocusable(false);
        dangXuatBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dangXuatBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dangXuatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(dangXuatBtn);
        jToolBar1.add(jSeparator8);

        mainTPL.setBackground(new java.awt.Color(102, 102, 102));
        mainTPL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTPLStateChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mainTPL);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thongTinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongTinBtnActionPerformed
        if (infoPnl == null) {
            infoPnl = new Info_GVPanel(this);
            mainTPL.addTab("Thông Tin", infoPnl);
        }
        mainTPL.setSelectedComponent(infoPnl);
    }//GEN-LAST:event_thongTinBtnActionPerformed

    private void thoiGBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoiGBBtnActionPerformed
        //        if (timeTablePnl == null) {
            //            timeTablePnl = new TimeTablePanel();
            //            mainTPL.addTab("Thời Gian Biểu", timeTablePnl);
            //        }
        mainTPL.setSelectedComponent(timeTablePnl);
        //        mainTPL.addTab("Thời Gian Biểu", timeTablePnl);
        //        mainTPL.setSelectedComponent(timeTablePnl);
    }//GEN-LAST:event_thoiGBBtnActionPerformed

    private void diemDanhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemDanhBtnActionPerformed
        //        if (rollUpPnl == null) {
            //            rollUpPnl = new RollUpMainPanel(this);
            //            mainTPL.addTab("Điểm Danh", rollUpPnl);
            //        }
        //            mainTPL.addTab("Điểm Danh", rollUpPnl);
        mainTPL.setSelectedComponent(rollUpPnl);
    }//GEN-LAST:event_diemDanhBtnActionPerformed

    private void traCuuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traCuuBtnActionPerformed
        //        if (lookUpPnl == null) {
            //            lookUpPnl = new LookUpPanel(this);
            //            mainTPL.addTab("Tra Cứu", lookUpPnl);
            //        }
        //        mainTPL.addTab("Tra Cứu", lookUpPnl);
        mainTPL.setSelectedComponent(lookUpPnl);
    }//GEN-LAST:event_traCuuBtnActionPerformed

    private void hopThuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hopThuBtnActionPerformed
        //        if (mailPnl == null) {
            //            mailPnl = new MailPanel(this);
            //            mainTPL.addTab("Hộp Thư", mailPnl);
            //        }
        //         mainTPL.addTab("Hộp Thư", mailPnl);
        mainTPL.setSelectedComponent(mailPnl);
    }//GEN-LAST:event_hopThuBtnActionPerformed

    private void dangXuatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatBtnActionPerformed
        //        LogInDialog logInDlg = new LogInDialog(this, true);
        //        logInDlg.setVisible(true);
        this.dispose();
        KetNoiSQL_GV.setMaGV("");
        loginDlg.setVisible(true);
    }//GEN-LAST:event_dangXuatBtnActionPerformed

    private void mainTPLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTPLStateChanged
        
//<editor-fold defaultstate="collapsed" desc="preventive Plan">
//        // cho nay fix bug hoi ngu nen khi doc code hoi kho hieu, phai ket hop
//        // them phan note da ghi chu moi hieu tai sao fix bug bang code nhu vay      
//        Class selectedMajorTab = mainTPL.getSelectedComponent().getClass();
//        if (rollUpPnl != null && lookUpPnl != null) {
//            // Do 2 tab nay co chua chuc nang update listBuoiHoc
//            // nen moi lan chuyen doi giua 2 tab la phai cap nhat lai listBuoiHoc tren tat ca pham vi
//            if (selectedMajorTab.equals(rollUpPnl.getClass())) {
//                //System.out.println("Tab: " + selectedMajorTab.getSimpleName());
//                if (rollUpPnl.getDiemDanhTPL().getComponentCount() > 0 && listBuoiHoc != null) {
//                    // DO BUG khi listBuoiHoc có buoiHoc được tạo mới
//                    listBuoiHoc = rollUpPnl.getListBuoiHoc();
//                    lookUpPnl.updateListBuoiHocAndShowTable(listBuoiHoc);
//                    // vào tab này thì update listBuoiHoc với data lấy ở tab cũ
//                    listBuoiHoc = lookUpPnl.getListBuoiHoc();
//                    Class selectedMinorTab = rollUpPnl.getDiemDanhTPL().getSelectedComponent().getClass();
//                    if (rollUpPnl.getLichDiemDanhPnl() != null
//                            && selectedMinorTab.equals(rollUpPnl.getLichDiemDanhPnl().getClass())) {
//                        RollUpCalendarPanel pnlTmp = rollUpPnl.getLichDiemDanhPnl();
//                        pnlTmp.updateListBuoiHocAndShowTable(listBuoiHoc);
//                    } else if (rollUpPnl.getDsDiemDanhPnl() != null
//                            && selectedMinorTab.equals(rollUpPnl.getDsDiemDanhPnl().getClass())) {
//                        RollUpListPanel pnlTmp = rollUpPnl.getDsDiemDanhPnl();
//                        pnlTmp.updateListBuoiHocAndShowTable(listBuoiHoc);
//                    } else if (rollUpPnl.getTaoDiemDanhPnl() != null
//                            && selectedMinorTab.equals(rollUpPnl.getTaoDiemDanhPnl().getClass())) {
//                        RollUpCreatePanel pnlTmp = rollUpPnl.getTaoDiemDanhPnl();
//                        pnlTmp.updateListBuoiHocAndShowTable(listBuoiHoc);
//                    }
//                }
//            } else if (selectedMajorTab.equals(lookUpPnl.getClass())) {
//                listBuoiHoc = rollUpPnl.getListBuoiHoc();
//                if (listBuoiHoc != null) {
//                    lookUpPnl.updateListBuoiHocAndShowTable(listBuoiHoc);
//                }
//            }
//        }
//</editor-fold>
        // cach xu ly moi: Chua test ky lam, truoc mat kha on :) 
        Class selectedMajorTab = mainTPL.getSelectedComponent().getClass();
        if (rollUpPnl != null && lookUpPnl != null) {
            // Do 2 tab nay co chua chuc nang update listBuoiHoc
            // nen moi lan chuyen doi giua 2 tab la phai cap nhat lai listBuoiHoc tren tat ca pham vi
            if (selectedMajorTab.equals(rollUpPnl.getClass())) {
                if (rollUpPnl.getDiemDanhTPL().getComponentCount() > 0 && listBuoiHoc == null) {
                    listBuoiHoc = rollUpPnl.getListBuoiHoc();
                }
                if (rollUpPnl.getDiemDanhTPL().getComponentCount() > 0 && listBuoiHoc != null) {
                    // vào tab này thì update listBuoiHoc với data lấy ở tab cũ
                    if (lookUpPnl.isListBuoiHocUpdated()) {
                        lookUpPnl.setListBuoiHocUpdated(false);
                        listBuoiHoc = lookUpPnl.getListBuoiHoc();
                    }
                    Class selectedMinorTab = rollUpPnl.getDiemDanhTPL().getSelectedComponent().getClass();
                    if (rollUpPnl.getLichDiemDanhPnl() != null
                            && selectedMinorTab.equals(rollUpPnl.getLichDiemDanhPnl().getClass())) {
                        RollUpCalendarPanel pnlTmp = rollUpPnl.getLichDiemDanhPnl();
                        pnlTmp.updateListBuoiHocAndShowTable(listBuoiHoc);
                    } else if (rollUpPnl.getDsDiemDanhPnl() != null
                            && selectedMinorTab.equals(rollUpPnl.getDsDiemDanhPnl().getClass())) {
                        RollUpListPanel pnlTmp = rollUpPnl.getDsDiemDanhPnl();
                        pnlTmp.updateListBuoiHocAndShowTable(listBuoiHoc);
                    } else if (rollUpPnl.getTaoDiemDanhPnl() != null
                            && selectedMinorTab.equals(rollUpPnl.getTaoDiemDanhPnl().getClass())) {
                        RollUpCreatePanel pnlTmp = rollUpPnl.getTaoDiemDanhPnl();
                        pnlTmp.updateListBuoiHocAndShowTable(listBuoiHoc);
                     }
                }
            } else if (selectedMajorTab.equals(lookUpPnl.getClass())) {
                if (listBuoiHoc == null) {
                    listBuoiHoc = lookUpPnl.getListBuoiHoc();
                }
                if (rollUpPnl.isListBuoiHocUpdated()) {
                    rollUpPnl.setListBuoiHocUpdated(false);
                    listBuoiHoc = rollUpPnl.getListBuoiHoc();
                    lookUpPnl.updateListBuoiHocAndShowTable(listBuoiHoc);
                }
            }
        }
    }//GEN-LAST:event_mainTPLStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangXuatBtn;
    private javax.swing.JButton diemDanhBtn;
    private javax.swing.JButton hopThuBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane mainTPL;
    private javax.swing.JButton thoiGBBtn;
    private javax.swing.JButton thongTinBtn;
    private javax.swing.JButton traCuuBtn;
    // End of variables declaration//GEN-END:variables
}
