/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoVien;

import Model.GiaoVien.ListBuoiHoc;
import javax.swing.JTabbedPane;

/**
 *
 * @author chuon
 */
public class RollUpMainPanel extends javax.swing.JPanel {

    private MainFormGV home;
    private RollUpCalendarPanel lichDiemDanhPnl;
    private RollUpListPanel dsDiemDanhPnl;
    private RollUpCreatePanel taoDiemDanhPnl;
    private static ListBuoiHoc listBuoiHoc;
    private static boolean listBuoiHocUpdated;
    /**
     * Creates new form RollUpPanel
     */
    public RollUpMainPanel(MainFormGV home) {
        initComponents();
        this.home = home;
        listBuoiHocUpdated = false;
        lichDiemDanhPnl = new RollUpCalendarPanel();
        diemDanhTPL.addTab("Lịch Điểm Danh", lichDiemDanhPnl);
        dsDiemDanhPnl = new RollUpListPanel(home);
        diemDanhTPL.addTab("Danh Sách Điểm Danh", dsDiemDanhPnl);
        taoDiemDanhPnl = new RollUpCreatePanel(home);
        diemDanhTPL.addTab("Tạo Điểm Danh", taoDiemDanhPnl);
        diemDanhTPL.setSelectedComponent(taoDiemDanhPnl);
    }

    public RollUpCalendarPanel getLichDiemDanhPnl() {
        return lichDiemDanhPnl;
    }

    public RollUpListPanel getDsDiemDanhPnl() {
        return dsDiemDanhPnl;
    }

    public RollUpCreatePanel getTaoDiemDanhPnl() {
        return taoDiemDanhPnl;
    }

    public JTabbedPane getDiemDanhTPL() {
        return diemDanhTPL;
    }

    public ListBuoiHoc getListBuoiHoc() {
        return listBuoiHoc;
    }
    
    public void setListBuoiHoc(ListBuoiHoc listBuoiHoc) {
        this.listBuoiHoc = listBuoiHoc;
    }

    public static boolean isListBuoiHocUpdated() {
        return listBuoiHocUpdated;
    }

    public static void setListBuoiHocUpdated(boolean listBuoiHocUpdated) {
        RollUpMainPanel.listBuoiHocUpdated = listBuoiHocUpdated;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lichDiemDanhBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        dsDiemDahBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        taoDiemDanhBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        diemDanhTPL = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lichDiemDanhBtn.setText("Lịch Điểm Danh");
        lichDiemDanhBtn.setFocusable(false);
        lichDiemDanhBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lichDiemDanhBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lichDiemDanhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lichDiemDanhBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(lichDiemDanhBtn);
        jToolBar1.add(jSeparator1);

        dsDiemDahBtn.setText("Danh Sách Điểm Danh");
        dsDiemDahBtn.setFocusable(false);
        dsDiemDahBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dsDiemDahBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dsDiemDahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsDiemDahBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(dsDiemDahBtn);
        jToolBar1.add(jSeparator2);

        taoDiemDanhBtn.setText("Tạo Điểm Danh");
        taoDiemDanhBtn.setFocusable(false);
        taoDiemDanhBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        taoDiemDanhBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        taoDiemDanhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taoDiemDanhBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(taoDiemDanhBtn);
        jToolBar1.add(jSeparator3);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        diemDanhTPL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        diemDanhTPL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                diemDanhTPLStateChanged(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐIỂM DANH");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diemDanhTPL, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diemDanhTPL, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dsDiemDahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsDiemDahBtnActionPerformed
//        if (dsDiemDanhPnl == null) {
//            dsDiemDanhPnl = new RollUpListPanel(home);
//            diemDanhTPL.addTab("Danh Sách Điểm Danh", dsDiemDanhPnl);
//        }
        diemDanhTPL.setSelectedComponent(dsDiemDanhPnl);
    }//GEN-LAST:event_dsDiemDahBtnActionPerformed

    private void lichDiemDanhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lichDiemDanhBtnActionPerformed
//        if (lichDiemDanhPnl == null) {
//            lichDiemDanhPnl = new RollUpCalendarPanel();
//            diemDanhTPL.addTab("Lịch Điểm Danh", lichDiemDanhPnl);
//        }
        diemDanhTPL.setSelectedComponent(lichDiemDanhPnl);
    }//GEN-LAST:event_lichDiemDanhBtnActionPerformed

    private void taoDiemDanhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taoDiemDanhBtnActionPerformed
//        if (taoDiemDanhPnl == null) {
//            taoDiemDanhPnl = new RollUpCreatePanel(home);
//            diemDanhTPL.addTab("Tạo Điểm Danh", taoDiemDanhPnl);
//        }
        diemDanhTPL.setSelectedComponent(taoDiemDanhPnl);
    }//GEN-LAST:event_taoDiemDanhBtnActionPerformed

    private void diemDanhTPLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_diemDanhTPLStateChanged
        // du lieu thao tac tren Panel nay la listBuoiHoc
        // listBuoiHoc chi thay doi khi thao tac trong RollUpCreatePanel
        // RollUpCalendarPanel + RollUpListPanel thay doi phu thuoc vao listBuoiHoc
        if (taoDiemDanhPnl != null) {
            listBuoiHoc = taoDiemDanhPnl.getListBuoiHoc();
            Class selectedTab = diemDanhTPL.getSelectedComponent().getClass();
            //System.out.println(selectedTab);
            if (lichDiemDanhPnl != null  && 
                    selectedTab.equals(lichDiemDanhPnl.getClass())) {
                // update listBuoiHoc + trigger showTable + filters trong tab RollUpCalendarPanel
                lichDiemDanhPnl.updateListBuoiHocAndShowTable(listBuoiHoc);
            } else if (dsDiemDanhPnl != null && 
                    selectedTab.equals(dsDiemDanhPnl.getClass())) {
                dsDiemDanhPnl.updateListBuoiHocAndShowTable(listBuoiHoc);
            }
        }
    }//GEN-LAST:event_diemDanhTPLStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane diemDanhTPL;
    private javax.swing.JButton dsDiemDahBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lichDiemDanhBtn;
    private javax.swing.JButton taoDiemDanhBtn;
    // End of variables declaration//GEN-END:variables
}
