/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.GiaoVien.MainFormGV;
import Model.BasicAttribute_Method;
import Model.GiaoVien.KetNoiSQL_GV;
import Model.SinhVien.KetNoiSQL_SV;
import View.SinhVien.MainFormSV;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author atree292000
 */
public class LogInDialog extends javax.swing.JFrame {

    private String tenDangNhap;
    private String matKhau;

    /**
     * Creates new form LogInDialog1
     */
    public LogInDialog() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản Lý Điểm Danh PTIT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        matKhauTxt = new javax.swing.JPasswordField();
        btnThoat = new javax.swing.JButton();
        tenDangNhapTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dangNhapBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Kozuka Mincho Pr6N H", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bạn chưa có tài khoản?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 220, 70));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/gpa-icon-32.png"))); // NOI18N
        jLabel9.setText("Mật Khẩu");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 90, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/logologin.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 120));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Liên hệ: 0569852108");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        matKhauTxt.setBackground(new java.awt.Color(0, 0, 0));
        matKhauTxt.setForeground(new java.awt.Color(255, 255, 255));
        matKhauTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matKhauTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(matKhauTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 244, 30));

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/Button-Close-icon-16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 140, 40));

        tenDangNhapTxt.setBackground(new java.awt.Color(0, 0, 0));
        tenDangNhapTxt.setForeground(new java.awt.Color(255, 255, 255));
        tenDangNhapTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenDangNhapTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tenDangNhapTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenDangNhapTxtActionPerformed(evt);
            }
        });
        getContentPane().add(tenDangNhapTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 244, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/Person-Male-Light-icon-24.png"))); // NOI18N
        jLabel6.setText("Tài Khoản");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 90, 30));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vui lòng đăng nhập tài khoản của bạn tại đây...");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 280, -1, 20));

        dangNhapBtn.setBackground(new java.awt.Color(255, 255, 255));
        dangNhapBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangNhapBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/Login-icon-16.png"))); // NOI18N
        dangNhapBtn.setText("Đăng Nhập");
        dangNhapBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dangNhapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangNhapBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dangNhapBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 140, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("Email: n18dccn095@student.ptithcm.edu.com");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 392, 480, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimage/close-up-calendar-orange-table-background-planning-business-meeting-travel-concept-204616424.jpg"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 540));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean kiemTraNgoaiLeTaiKhoan(String tenDangNhap, String matKhau) {
        int ngoaiLeTenDangNhap = getNgoaiLeTenDangNhap(tenDangNhap);
        if (ngoaiLeTenDangNhap == 1) {
            JOptionPane.showMessageDialog(this, "Tên Đăng Nhập Không Được Bỏ Trống",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (ngoaiLeTenDangNhap == 2) {
            JOptionPane.showMessageDialog(this, "Tên Đăng Nhập Tối Thiểu 5 Ký Tự",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (ngoaiLeTenDangNhap == 3) {
            JOptionPane.showMessageDialog(this, "Tên Đăng Nhập Ký Tự Đầu Tiên Không Thể Là Số",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (ngoaiLeTenDangNhap == 4) {
            JOptionPane.showMessageDialog(this, "Tên Đăng Nhập Ko Khoảng Trắng, Không Ký Tự Đặc Biệt",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        int ngoaiLeMatKhau = BasicAttribute_Method.getNgoaiLeMatKhau(matKhau);
        if (ngoaiLeMatKhau == 1) {
            JOptionPane.showMessageDialog(this, "Mật Khẩu Không Được Bỏ Trống",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (ngoaiLeMatKhau == 2) {
            JOptionPane.showMessageDialog(this, "Mật Khẩu Quá Dài",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private int getNgoaiLeTenDangNhap(String tenDangNhap) {
        if (tenDangNhap.equals("")) {
            return 1;
        }
        if (tenDangNhap.length() < 5) {
            return 2;
        }
        if (tenDangNhap.codePointAt(0) >= 48 && tenDangNhap.codePointAt(0) <= 57) {
            return 3;
        }
        String patternTenDangNhap = "^[a-zA-Z]([a-zA-Z0-9]+){4,20}";
        if (!tenDangNhap.matches(patternTenDangNhap)) {
            return 4;
        }
        return 0;
    }

    private int getIDLoaiTaiKhoan(String tenDangNhap, String matKhau) {
        // tra ve IDLoaiTK voi cac input tren
        // tim thay tra ve binh thuong
        // ko thay thi return -1;
        // nho dung prepareStatement de phong loi sql injection
        // Khi kiem tra ten dang nhap ko phan biet chu in hoa hay chu thuong (nhu trong UIS)
        int ketQua = -1;

        String user = "sa";
        String pass = "123";
        String url = "jdbc:sqlserver://localhost:1433;databaseName=CNPHANMEM3";
        Connection connection = null;

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(url, user, pass);
            String sql = "SELECT IDLoaiTK FROM dbo.TaiKhoan WHERE [User]=? AND Pass=? ";
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(1, tenDangNhap);
            ps.setString(2, matKhau);

            ResultSet resultSet = ps.executeQuery();

            while (resultSet.next()) {
                ketQua = resultSet.getInt("IDLoaiTK");
            }

        } catch (Exception ex) {
            System.out.println(ex);
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(LogInDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

        return ketQua;
    }

    private boolean kiemTraTonTaiTaiKhoan(String tenDangNhap, String matKhau) {
        boolean ketQua = BasicAttribute_Method.kiemTraTonTaiTaiKhoan(tenDangNhap, matKhau);
        if (ketQua == false) {
            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu",
                    "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        }
        return ketQua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tenDangNhapTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenDangNhapTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenDangNhapTxtActionPerformed

    private void dangNhapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangNhapBtnActionPerformed
        tenDangNhap = tenDangNhapTxt.getText();
        matKhau = matKhauTxt.getText();
        if (kiemTraNgoaiLeTaiKhoan(tenDangNhap, matKhau)) {
            if (kiemTraTonTaiTaiKhoan(tenDangNhap, matKhau)) {
                int idLoaiTK = getIDLoaiTaiKhoan(tenDangNhap, matKhau);
                // neu tai khoan la SV
                if (idLoaiTK == 1) {
                    KetNoiSQL_SV.setMssv(tenDangNhap);
                    MainFormSV mainForm = new MainFormSV(this);
                    this.setVisible(false);
                    mainForm.setVisible(true);
                } else if (idLoaiTK == 2) {
                    KetNoiSQL_GV.setMaGV(tenDangNhap);
                    MainFormGV mainForm = new MainFormGV(this);
                    this.setVisible(false);
                    mainForm.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi DataBase Không Lấy Được Dữ Liệu idLoaiTK",
                            "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_dangNhapBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton dangNhapBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField matKhauTxt;
    private javax.swing.JTextField tenDangNhapTxt;
    // End of variables declaration//GEN-END:variables
}
